# YAML（YAML Ain't Markup Language）
#    YAML A Markup Language：    是一个标记语言
#    YAML isn't Markup Language：不是一个标记语言；
# 标记语言：
# 以前的配置文件；大多都使用的是  xxx.xml文件；
# YAML：以数据为中心，比json、xml等更适合做配置文件；

# 1、基本语法
# k:(空格)v：表示一对键值对（空格必须有）；
# 以空格的缩进来控制层级关系；只要是左对齐的一列数据，都是同一个层级的
# 属性和值也是大小写敏感；

# 字面量：普通的值（数字，字符串，布尔）：
# k: v：字面直接来写
#       字符串默认不用加上单引号或双引号
#       "":双引号；会转义字符串里面的特殊字符；特殊字符会作为本身想表示的意思
#         如：name: "zhangsan \n lisi"：输出：zhangsan 换行 lisi
#       '':单引号；不会转义特殊字符，特殊字符最终只是一个普通的字符串数据
#         如：name: 'zhangsan \n lisi'：输出：zhangsan \n lisi

# 对象、Map（属性和值）（键值对）：
# k:v：在下一行来写对象的属性和值的关系；注意缩进
#   对象还是k: v的方式
#   friends:
#     lastName: zhangsan
#     age: 20
#   行内写法：
#   friends: {lastName: zhangsan,age: 18}

# 数组（List、Set）：
# 用-值表示数组中的一个元素
# pets:
#   - cat
#   - dog
#   - pig
# 行内写法：
# pets: [cat,dog,pig]

#yml支持多文档块方式

server:
  port: 8081

person:
#  lastName: 王五
  last-name: 王五
  age: 18
  birth: 2020/02/02
  maps: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: 小狗
    age: 2

dog:
  name: 老狗
  age: 10
